#!/bin/sh
# Launch sxhkd for keybinding
xrandr --output eDP-1 --auto --primary --pos 0x0
xrandr --output HDMI-1 --mode 2880x1620 --scale 1.2x1.2 --pos -768x-1944

pgrep -x sxhkd >/dev/null || sxhkd &
bspc config border_width 2
bspc config window_gap 8
bspc config focused_border_color "#89b4fa"
bspc config normal_border_color "#313244"

# Automatically start polybar
~/.config/polybar/launch.sh &
~/.config/bspwm/monitors/auto_detect.sh &
