#################
### AUTOSTART ###
#################

xwayland {
  force_zero_scaling = true
}

exec-once = wal -i ~/.config/wallpapers/wp12471694.jpg
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = setxkbmap us
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = bash -c 'sleep 1.5 && waybar'
exec-once = ~/.config/hypr/scripts/monitor-detect.sh
exec-once = hyprpaper

