# Variables
$inFocusOpacity = 0.97
$notInFocusOpacity = 0.9

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*


# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# Opacity rules
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*().*$,
windowrulev2 = opacity 1 1, class:^(waybar)$
windowrulev2 = opacity 1 0.7,class:.*(kitty).*$,
windowrulev2 = fullscreen, class:^(Lunar Client.*)$
windowrulev2 = tile, class:^(Lunar Client.*)$
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,class:^(firefox|brave|chromium|librewolf|qutebrowser|zen-browser)$,
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Spotify).*$,
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Discord).*$,
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Telegram).*$,
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Code).*$,
windowrulev2 = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Thunar|nemo).*$,
